- s3path.py
This makes it operating system independent, as at the moment, this library doesn't work under Windows.
Nothing changes, as it was used from `os` already.
```python
>>> from posix import stat_result
>>> stat_result
<class 'os.stat_result'>
```
> Import stat_result from os instead of posix

- s3path.py
Closes #47 
This solves the problem, at least for my case, where I cannot pass the chunk size to the `read([size])` method.
Be warned that I'm not so familiar with the details of the botocore API, so the `*args, **kwargs` may or may not be superfluous. A potential alternative solution could look something like
```python
def read(self, size=None):
return self._string_parser(self._streaming_body.read(size))
```
> Allow passing of chunk size to read

- s3path.py
- tests/test_path_operations.py
This PR aims to fix the `S3KeyReadableFileObject` line iteration.
There were a few issues:
* Everytime `readline` was called a new generator was created from `_streaming_body.iter_lines`
* The `__next__` method was calling `readline` and this method never raises `StopIteration`
* `readlines` was iterating over `readline` that  never raises `StopIteration`
Now the iterator is kept and reused so we can start consuming the file from one method and then continue from another.
We can also iterate over `S3KeyReadableFileObject` as it will read the lines and stop when it should.
See #53
> fix: Fixes S3KeyReadableFileObject line iteration

- s3path.py
- tests/test_path_operations.py
To be compliant with the base writelines method the new line character should not be added.
From the documentation https://docs.python.org/2/library/stdtypes.html#file.writelines :
> The name is intended to match readlines(); writelines() does not add line separators.
There was also an issue where the double call to `_string_parser` (once in `writlines` and then in `write`) was raising an error:
>  TypeError: a bytes-like object is required, not 'str'
See #52
> fix: Fixes writelines method of S3KeyWritableFileObject

- s3path.py
- setup.py
- tests/test_path_operations.py
This PR make S3Path respects the file interface concerning the newline characters in the `readlines` and `readline` methods.
> f.readline() reads a single line from the file; a newline character (\n) is left at the end of the string, and is only omitted on the last line of the file if the file doesn’t end in a newline.
See https://docs.python.org/3/tutorial/inputoutput.html#methods-of-file-objects
Parent issue: #56
We have to be aware that this feature is creating a **breaking change** since it modifies the output of `readlines` and `readline`.
I think this is for the best because it will get the project closer to the interface it tries to imitate.
> feat: Keep newline characters in readline and readlines

- s3path.py
This simply makes the spelling consistent between `object_summery` and `resource.ObjectSummary`.
> minor: replace object_summery with object_summary

- s3path.py
I found that the new Smart Open API for the multipart_upload and get_object kwargs was not being used. I fixed as explained here:
[MIGRATING_FROM_OLDER_VERSIONS.rst](https://github.com/RaRe-Technologies/smart_open/blob/develop/MIGRATING_FROM_OLDER_VERSIONS.rst)
> Added new Smart-Open api multipart_upload and get_object kwargs

- s3path.py
This should resolve #77 for most cases.
See the discussion in #77 for further thoughts. This isn't intended to be a final fix, since I think we need to decide what is the proper behavior of the `.as_uri()` method. But I think it might be suitable for the next release. Thoughts?
> Don't encode as URI for smart_open

- .github/workflows/testing.yml
- docs/interface.rst
- s3path.py
- setup.py
- tests/test_not_supported.py
- Add support for CI to test on 3.10
- Explicitly set the accessor. Before 3.9 the `_accessor` was not modified but with 3.10+ `Path` now modifies the `_accessor`. So we have to explicitly override it.
- Add `follow_symlinks` argument to the `stat()` (and raise a `NotImplementError` if it is falsy)
Fixes #94.
> Python 3.10 compatibility changes

- Pipfile
- s3path.py
- setup.py
- tests/test_s3path_configuration.py
[[PEP 632]](https://peps.python.org/pep-0632/) deprecates the `distutils` module of the Python standard library. This PR removes `distutils` as a dependency of `s3path` and uses the [packaging](https://github.com/pypa/packaging) library instead.
> [PEP 632] Remove deprecated distutils

- .github/workflows/testing.yml
- s3path.py
- setup.py
- tests/test_path_operations.py
Add support to python 3.11 by overriding the methods that were relying on `_Accessor` in cpython
Parent task: #112
> feat: Add support for python 3.11

- docs/interface.rst
- s3path.py
- tests/test_path_operations.py
Closes #125 
An improvement that could be done later is to allow to change the method, for example by adding an argument `mode: Literal["r", "w"] = "r"` . Using "w" would allow a POST and thus an upload. GET would stay the default as it's the most used mode.
> :sparkles: Add a get_presigned_url method for GET operations

- README.rst
- docs/interface.rst
- s3path.py
- tests/test_path_operations.py
This PR addresses issue #126 by
1. Adding a `VersionedS3Path` class to the public API
2. Adding a `st_version_id` property to `StatResult`
3. Adding automated tests for the new functionality in `tests/test_path_operations.py`
4. Adding appropriate documentation to `README.rst` and `docs/interface.rst`
* `VersionedS3Path` inherits from `S3Path` but adds a `version_id` parameter to the various constructor methods. In order to follow the Liskov substitution principle, this parameter is made optional with a default value of `None`. We thought that if a user does not supply a value for this parameter, then the returned instance should be of type `S3Path` instead of `VersionedS3Path`. Hence the necessity for overriding the `__new__` constructor.
* We think that while relative paths and …
> Feature: `VersionedS3Path`

- README.rst
- docs/interface.rst
- s3path.py
This PR includes the documentation to go with the new `VersionedS3Path` and `PureVersionedS3Path` classes introduced in #139.
Additionally:
1. The `VersionedS3Path.__repr__` method was moved to the `PureVersionedS3Path` class so that both classes now have the correct representation string.
2. The `pathlib.PurePath.joinpath` method was overridden in `PureS3Path` to account for the new possibilities created with the addition of the new `VersionedS3Path` and `PureVersionedS3Path` classes.
> Update documentation around `VersionedS3Path` and `PureVersionedS3Path`

- setup.cfg
This should solve:
```
~/.conda/envs/forge/lib/python3.11/site-packages/setuptools/dist.py:498: SetuptoolsDeprecationWarning: Invalid dash-separated options
!!
********************************************************************************
Usage of dash-separated 'license-file' will not be supported in future
versions. Please use the underscore name 'license_file' instead.
This deprecation is overdue, please update your project and remove deprecated
calls to avoid build errors in the future.
See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
********************************************************************************
!!
opt = self.warn_dash_deprecation(opt, section)
~/.conda/envs/forge/lib/python3.11/site-packages/setuptools/config/setupcfg.py:293: …
```
> Fix license-file → license_files

- docs/comparison.rst
Fixes a super tiny typo in `docs/comparison.rst`
> Fix Small Typo in `comparison.rst`

- s3path/current_version.py
This is a `DeprecationWarning` in Python<3.12 and a `SyntaxWarning` in Python>=3.12 since `\Z` is an invalid escape sequence. In every case, this should be made a raw string as also described in the according [change note]:
A backslash-character pair that is not a valid escape sequence now
generates a SyntaxWarning, instead of DeprecationWarning. For example,
re.compile("\d+\.\d+") now emits a SyntaxWarning ("\d" is an invalid
escape sequence, use raw strings for regular expression:
re.compile(r"\d+\.\d+")). In a future Python version, SyntaxError will
eventually be raised, instead of SyntaxWarning.
[change note]: https://docs.python.org/3.12/whatsnew/3.12.html#other-language-changes
```shell
❯ docker run --rm -it python:3.11-slim python -c "a = ''; a += '/*\Z'; print(a)"
/*\Z
❯ docker …
```
> Fix SyntaxWarning/DeprecationWarning

- s3path/__init__.py
- s3path/current_version.py
- s3path/old_versions.py
- setup.py
- tests/test_path_operations.py
This is a fix for issue raised in this comment [here](https://github.com/liormizr/s3path/issues/160#issuecomment-2056384036)
> fix_glob_duble_path_issue

- docs/comparison.rst
- tests/test_path_operations.py
It's an extremely common use case to want to copy a file to/from/between S3 buckets. The `dst.write_text(src.read_text())` solution is simple, but not viable for large files.
Luckily, I came across [this gem](https://github.com/liormizr/s3path/issues/88#issuecomment-1551200162) by @gabrieldemarmiesse using `shutil.copyfileobj`. This works well for all combinations of `pathlib.Path` and `s3path.S3Path` as source and destination.
That comment is very difficult to discover, especially when searching for issues. Some more prominent discussions are https://github.com/liormizr/s3path/issues/98 (no solution) and https://github.com/liormizr/s3path/issues/44 (overly-complicated solution). Thus I think we should codify the solution in the documentation to make it easily discoverable.
---
I tried a …
> Add example of buffered copy to docs

- .github/workflows/testing.yml
- s3path/current_version.py
- setup.py
- tests/test_path_operations.py
- tests/test_s3path_configuration.py
Changes:
- `PurePath._flavour` is now known as `PurePath.parser`.
- `PurePath._load_parts()` is now gone and replaced by `PurePath._raw_path`.
- Disable old glob feature when using Python 3.13 (a lot of changes were done in official `pathlib`).
> Add Python 3.13 compatibility

- s3path/py.typed
- setup.py
Add `py.typed` file so that mypy can access the type hints. See https://mypy.readthedocs.io/en/stable/installed_packages.html#creating-pep-561-compatible-packages and https://peps.python.org/pep-0561/
closes #176
> add py.typed file

- s3path/accessor.py
The previous behavior forced the full results of `Path.iterdir` to be fetched and buffered internally before any results could be returned. This causes significant delays for large bucket directories.
All other parts of call stack support streaming results lazily, so this change allows the `Path.iterdir` iterator to start returning results as soon as the first page of results is received from the S3 API.
The `accessor.listdir` function is an internal API, so this change shouldn't cause any disruption; it is only a significant performance improvement.
> Ensure that `Path.iterdir` is fetched lazily

- s3path/old_versions.py
Hello! I really like this repo, managing S3 data like pathlib Path's is awesome. I'd like to use your s3path in an internal project. However, a security scan by Fortify revealed this one "vulnerability" so I wanted to contribute to its removal, so our security guys will be happy.
This is what the Fortify had to say about the offending line `access_key = secret_key = token = None`:
> 
> "Null encryption keys can compromise security in a way that is not easy to remedy.
> 
> Assigning None to encryption key variables is a bad idea because it can allow attackers to expose sensitive and encrypted information. Not only does using a null encryption key significantly reduce the protection afforded by a good encryption algorithm, but it also makes fixing the problem extremely difficult. After the …
> Removed null encryption key vulnerability

- s3path/current_version.py
Thanks for adding type hints to s3path!
I saw your comments about type hints adding to the maintenance burden, and I don't want that to be the case because the benefit of type hints are great. This is a PR to address what I believe is an error in the type hint implementation added in 0.6.3.
Closes #198 
This PR changes the return type of `PureS3Path.from_uri` and `PureS3Path.from_bucket_key` to be `Self` instead of `PureS3Path`. Both class methods return an instance of `cls` which is not necessarily a `PureS3Path` if the class method is invoked from a subclass.
```
>> S3Path.from_uri('s3://bucket/key')
<< PureS3Path('/bucket/key')
>> PureS3Path.from_uri('s3://bucket/key')
<< PureS3Path('/bucket/key')
>> S3Path.from_uri('s3://bucket/key')
<< S3Path('/bucket/key')
>> …
```
> Change return type of PureS3Path class methods to Self
